### ISSUE TITLE
Add Vivaldi support

### ISSUE THREAD

**Issue by darkarth00** [Elements6007/ReturnYoutubeSort#14]
Hello,

It would be cool, if you could make it work right for Vivaldi. Vivaldi is a heavy individualized chrome based browser. The extension basicly works. But it has the issue that it shows the three oldest videos on the top and then it's going on with the newest videos.

**Comment by Elements6007** [comment]
Hi, I apologize but at this time I do not really have time to port this extension to browsers like Vivaldi. It should work because it is chromium based but I could not find a solution at a glance. If you or someone else would like to debug the issue that would be great :)

**Comment by Elements6007** [comment]
EOL is near. closing.
