### ISSUE TITLE
Doesn't work with the BetterTTV Extensions on Chrome

### ISSUE THREAD

**Issue by RenovationDev** [Elements6007/ReturnYoutubeSort#18]
I noticed it didn't work for me and found out it doesn't work if I have the BetterTTV extension on, just so you know.

(I use Chrome)

**Comment by Elements6007** [comment]
could you describe exactly what is not working?(like button not showing, not inverting, etc...) I just added the BetterTTV extension along with this and it works fine for me.

**Comment by RenovationDev** [comment]
For me the Button dosn't show up but only when i have BetterTTV on

**Comment by Elements6007** [comment]
Interesting, It works fine for me. If anyone else has this issue ill reopen it.
