### ISSUE TITLE
the videos appear in the wrong order in each bar

### ISSUE THREAD

**Issue by Mani-cwaf** [Elements6007/ReturnYoutubeSort#19]
I know that it's because the extension completely flips the direction the videos are displayed, but it's annoying that before it was showing 100-96, 95-92, 91-87, 86- 82, 81-77, etc, now it's 4-1, 8-5, 12-9, 16-13, etc, when it should be 1-4, 5-8, 9-12, 13-16, 17-20

**Comment by Elements6007** [comment]
Oh wow. I never noticed that it was doing that, turns out `flex-direction: row-reverse;` was not working properly. I'll be releasing a patch for this asap. Thank you!

**Comment by Elements6007** [comment]
fixed in v1.2.1 patch.
